# Generated by Django 3.1.4 on 2021-02-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcontact',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
