# Generated by Django 3.1.2 on 2020-11-08 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='image_contact',
            field=models.ImageField(blank=True, default='images_contacts/placeholder.jpg', null=True, upload_to='images_contacts', verbose_name='imagecontact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='url',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
