# Generated by Django 3.1.2 on 2020-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default=None, upload_to=None),
            preserve_default=False,
        ),
    ]
