# Generated by Django 3.1.4 on 2021-02-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tagcontact_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindercontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='dashboard.contact'),
        ),
    ]
