# Generated by Django 3.1.2 on 2020-11-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201101_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AddField(
            model_name='contact',
            name='image_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Photo'),
        ),
    ]
