# Generated by Django 3.1.3 on 2020-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_contact_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.TextField(blank=True),
        ),
    ]
