# Generated by Django 3.1.2 on 2020-11-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201101_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.TextField(default='Oviedo'),
            preserve_default=False,
        ),
    ]
