# Generated by Django 3.1.2 on 2020-11-02 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_contact_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image_avatar',
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='url',
            field=models.SlugField(default='dddd', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
