# Generated by Django 3.1.6 on 2021-02-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210211_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecontact',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
