# Generated by Django 3.1.2 on 2020-11-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201102_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
