# Generated by Django 3.1.6 on 2021-02-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencecontact',
            name='list_photos',
        ),
        migrations.AddField(
            model_name='experiencecontact',
            name='images',
            field=models.ManyToManyField(to='dashboard.ImageModel'),
        ),
    ]
