# Generated by Django 3.1.2 on 2020-11-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201102_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
