# Generated by Django 3.1.6 on 2021-02-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210220_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecontact',
            name='images',
            field=models.ManyToManyField(related_name='images', to='dashboard.ImageModel'),
        ),
    ]
