# Generated by Django 3.1.6 on 2021-02-21 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210221_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
