# Generated by Django 3.1.3 on 2020-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_experiencecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecontact',
            name='list_photos',
            field=models.TextField(blank=True),
        ),
    ]
