# Generated by Django 3.1.6 on 2021-03-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_imagemodel_upload_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindercontact',
            name='days_recursive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remindercontact',
            name='recursive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remindercontact',
            name='type',
            field=models.CharField(choices=[('MN', 'MANUAL'), ('TC', 'TOCH'), ('BT', 'BIRTHDAY')], default='MN', max_length=2),
        ),
    ]
