# Generated by Django 3.1.6 on 2021-03-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210311_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='keep_in_touch',
            field=models.CharField(choices=[('007', 'Cada semana'), ('014', 'Cada dos semana'), ('030', 'Una vez al mes'), ('060', 'Cada dos meses'), ('000', 'No recordar')], max_length=3),
        ),
    ]
