# Generated by Django 3.1.4 on 2020-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_musiccontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccontact',
            name='url_artist',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
