# Generated by Django 3.1.4 on 2020-12-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_musiccontact_url_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccontact',
            name='photo_artist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musiccontact',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musiccontact',
            name='url_artist',
            field=models.TextField(blank=True),
        ),
    ]
