# Generated by Django 3.1.4 on 2020-12-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20201229_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccontact',
            name='popularity',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
