# Generated by Django 3.1.4 on 2020-12-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_musiccontact_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccontact',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
