# Generated by Django 3.1.4 on 2020-12-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20201229_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccontact',
            name='id_artist',
            field=models.TextField(blank=True),
        ),
    ]
