# Generated by Django 3.1.4 on 2021-01-01 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0018_musiccontact_id_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.TextField()),
                ('surnames', models.TextField(blank=True)),
                ('relation_type', models.CharField(choices=[('Relaciones_amorosas', (('001', 'esposa'), ('002', 'amante'), ('003', 'ex - novio'))), ('Relaciones_familiares', (('4', 'hijo / hija'), ('5', 'hermano / hermana'), ('6', 'abuelo / abuela'), ('7', 'nieto / nieta'), ('8', 'tío / tía'), ('9', 'sobrino / sobrina'), ('10', 'primo / prima'), ('11', 'padrino / madrina'), ('12', 'ahijado / ahijada'), ('13', 'padrastro / madrastra'), ('14', 'hijastro / hijastra'))), ('Relaciones_de_amistad', (('15', 'amigo / amiga'), ('16', 'mejor amigo / amiga'), ('17', 'ex - novio'))), ('Relaciones_de_laborales', (('18', 'compañero / compañera'), ('19', 'jefe / jefa')))], max_length=3)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
