# Generated by Django 3.1.4 on 2021-01-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20210102_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycontact',
            name='relation_type',
            field=models.CharField(choices=[('Relaciones amorosas', (('001', 'Esposo / esposa'), ('002', 'Amante'), ('003', 'Ex - novio / novia'))), ('Relaciones familiares', (('4', 'Hijo / hija'), ('5', 'Hermano / hermana'), ('6', 'Abuelo / abuela'), ('7', 'Nieto / nieta'), ('8', 'Tío / tía'), ('9', 'Sobrino / sobrina'), ('10', 'Primo / prima'), ('11', 'Padrino / madrina'), ('12', 'Ahijado / ahijada'), ('13', 'Padrastro / madrastra'), ('14', 'Hijastro / hijastra'))), ('Relaciones de amistad', (('15', 'Amigo / amiga'), ('16', 'Mejor amigo / amiga'), ('17', 'Ex - novio'))), ('Relaciones de laborales', (('18', 'Compañero / compañera'), ('19', 'Jefe / jefa')))], max_length=3),
        ),
    ]
