# Generated by Django 3.1.4 on 2021-01-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210102_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='keep_in_touch',
            field=models.CharField(choices=[('001', 'Cada semana'), ('001', 'Cada dos semana'), ('003', 'Una vez al mes'), ('004', 'Cada dos meses'), ('000', 'No recordar')], default='000', max_length=3),
            preserve_default=False,
        ),
    ]
