# Generated by Django 3.1.4 on 2021-01-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_contact_keep_in_touch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='surnames',
            field=models.TextField(blank=True),
        ),
    ]
