# Generated by Django 3.1.4 on 2021-01-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20210110_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
