# Generated by Django 3.1.4 on 2021-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='remember_birthday',
            field=models.BooleanField(default=False),
        ),
    ]
