# Generated by Django 3.1.4 on 2021-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remindercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindercontact',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
