# Generated by Django 3.1.4 on 2021-01-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20210111_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindercontact',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
