# Generated by Django 3.1.4 on 2021-01-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20210111_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindercontact',
            name='days',
            field=models.IntegerField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
