# Generated by Django 3.1.4 on 2021-01-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_remindercontact_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindercontact',
            name='days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
