# Generated by Django 3.1.4 on 2021-01-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20210112_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remindercontact',
            name='days',
        ),
    ]
