# Generated by Django 3.1.4 on 2021-01-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_remindercontact_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindercontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='dashboard.contact'),
        ),
    ]
