# Generated by Django 3.1.4 on 2021-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validated_mail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
