# Generated by Django 3.1.2 on 2020-11-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts_created',
            field=models.IntegerField(default=0),
        ),
    ]
