# Generated by Django 3.1.6 on 2021-02-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210210_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='music_experience',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
