# Generated by Django 3.1.6 on 2021-02-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_music_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='music_experience',
            new_name='experience_active',
        ),
    ]
