# Generated by Django 3.1.3 on 2020-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validated_mail',
            field=models.BooleanField(default=False),
        ),
    ]
