# Generated by Django 3.1.3 on 2020-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_validated_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_validated_mail',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
