# Generated by Django 3.1.4 on 2021-01-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_family_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='music_active',
            field=models.IntegerField(default=0),
        ),
    ]
