# Generated by Django 3.1.4 on 2021-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_music_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='common_active',
            field=models.IntegerField(default=0),
        ),
    ]
