# Generated by Django 3.1.4 on 2021-01-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_common_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note_active',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='common_active',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='contacts_created',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_active',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='music_active',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
