# Generated by Django 3.1.4 on 2021-01-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210105_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts_active',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
